export default {
    "it": {
        "common$about": "Su di me",
        "common$contacts": "Contatti",
        "common$moreInfo": "Più Informazioni",
        "common$lessInfo": "Meno Informazioni",
        "common$skills": "Skills",
        "about$presentation": "Inventare cose mi è sempre piaciuto: sin da piccolo amavo creare storie e oggetti. Nel 2018 ho trovato la mia passione per lo sviluppo web, da allora non sono riuscito a smettere. Ho continuato a studiare e a cercare nuove strade per costruire ciò che volevo.",
        "contacts$phone": "Telefono:",
        "contacts$address": "Indirizzo:",
        "contacts$mail": "Email:",
        "data$phone": "3500698468",
        "data$address": "Via dei passatori 65, 41032 Cavezzo (Mo)",
        "data$mail": "masimirko101@gmail.com",
    },
    "en": {
        "common$about": "About me",
        "common$contacts": "Contacts",
        "common$moreInfo": "More Info",
        "common$lessInfo": "Less Info",
        "common$skills": "Skills",
        "about$presentation": "I always liked creating things; since I was little, I enjoyed inventing stories and objects. As an adult, I've learned how to funnel my creativity into coding. I approached web development in 2018, and since then, I couldn't get enough of it. I began building projects in my free time, constantly learning new things and ways to create what I want.",
        "contacts$phone": "Phone:",
        "contacts$address": "Address:",
        "contacts$mail": "Email:",
        "data$phone": "+39 3500698468",
        "data$address": "Via dei passatori 65, 41032 Cavezzo (Mo) - Italy",
        "data$mail": "masimirko101@gmail.com",
    },
};