export default {
    "it": {
        "common$about": "Su di me",
        "common$contacts": "Contatti",
        "common$moreInfo": "Più Informazioni",
        "common$lessInfo": "Meno Informazioni",
        "common$skills": "Skills",
        "common$from": "Da:",
        "common$to": "A:",
        "common$inRole": "Nel ruolo ho:",
        "common$technologies": "Tecnologie usate:",
        "common$experience": "Esperienza",
        "about$presentation": "Inventare cose mi è sempre piaciuto: sin da piccolo amavo creare storie e oggetti. Nel 2018 ho trovato la mia passione per lo sviluppo web, da allora non sono riuscito a smettere. Ho continuato a studiare e a cercare nuove strade per costruire ciò che volevo.",
        "contacts$phone": "Telefono:",
        "contacts$address": "Indirizzo:",
        "contacts$mail": "Email:",
        "data$phone": "3500698468",
        "data$address": "Via dei passatori 65, 41032 Cavezzo (Mo)",
        "data$mail": "masimirko101@gmail.com",
        "job_1$title": "Unity Developer",
        "job_1$from": "January 2023",
        "job_1$to": "",
        "job_1$company": "Freelance",
        "job_1$description": "n questo ruolo, ho lavorato alla creazione e allo sviluppo di giochi 3D utilizzando il motore di gioco Unity e il linguaggio di programmazione C#.",
        "job_1$keypoints": "Implementato meccaniche di gioco, animazioni e IA dei personaggi|\nCollaborato con artisti e designer per garantire una realizzazione fedele dei concetti di gioco|\nContribuito alla creazione di librerie e utilità per facilitare e velocizzare lo sviluppo dei progetti",
        "job_1$technologies": "Unity, C#, Blender",
        "job_2$title": "Frontend Developer",
        "job_2$from": "Novembre 2020",
        "job_2$to": "Dicembre 2022",
        "job_2$company": "Melazeta",
        "job_2$description": "Nella posizione ho lavorato principalmente come sviluppatore frontend, creando siti web, web app ed esperienze interattive.",
        "job_2$keypoints": "Realizzato il frontend di siti web utilizzando SASS, Twig e Stimulus.js, partendo da template di Adobe XD|\nCreato giochi interattivi impiegando Adobe Animate e Javascript|\nSviluppato web app con l'utilizzo di Typescript, React.js, React Hooks e Redux/Jotai|\nCompletato task backend impiegando il framework PHP Symfony",
        "job_2$technologies": "Twig, SASS, Tailwind, React.js, React Native, Symfony",
        "job_3$title": "Frontend Developer",
        "job_3$from": "Agosto 2018",
        "job_3$to": "Settembre 2020",
        "job_3$company": "Addazzle Mgmt",
        "job_3$description": "Manutenzione, e creazione di template per siti e-commerce.",
        "job_3$keypoints": "costruito SPA utilizzando React.js, HTML5, CSS3, Javascript ES6|\nAggiornato progetti già esistenti utilizzando Redux, e React Router|\nAggiornato progetti già esistenti permettendogli di sfruttare React Hooks",
        "job_3$technologies": "HTML, CSS, Javascript, React.js",
    },
    "en": {
        "common$about": "About me",
        "common$contacts": "Contacts",
        "common$moreInfo": "More Info",
        "common$lessInfo": "Less Info",
        "common$skills": "Skills",
        "common$from": "From:",
        "common$to": "To:",
        "common$inRole": "In this role, I:",
        "common$technologies": "Technologies used:",
        "common$experience": "Experience",
        "about$presentation": "I always liked creating things; since I was little, I enjoyed inventing stories and objects. As an adult, I've learned how to funnel my creativity into coding. I approached web development in 2018, and since then, I couldn't get enough of it. I began building projects in my free time, constantly learning new things and ways to create what I want.",
        "contacts$phone": "Phone:",
        "contacts$address": "Address:",
        "contacts$mail": "Email:",
        "data$phone": "+39 3500698468",
        "data$address": "Via dei passatori 65, 41032 Cavezzo (Mo) - Italy",
        "data$mail": "masimirko101@gmail.com",
        "job_1$title": "Unity Developer",
        "job_1$from": "January 2023",
        "job_1$to": "",
        "job_1$company": "Freelance",
        "job_1$description": "In this role, I worked on the creation and development of 3D games using the Unity game engine and the C# programming language.",
        "job_1$keypoints": "Implemented game mechanics, character animations, and AI|\nCollaborated with artists and designers to ensure faithful realization of game concepts|\nContributed to the creation of libraries and utilities to ease and speed up project development",
        "job_1$technologies": "Unity, C#, Blender",
        "job_2$title": "Frontend Developer",
        "job_2$from": "November 2020",
        "job_2$to": "December 2022",
        "job_2$company": "Melazeta",
        "job_2$description": "In my role, I primarily worked as a Frontend Developer, creating websites, web apps, and interactive experiences. During periods of heavy workload, I also assisted the backend developers with small tasks",
        "job_2$keypoints": "Created website frontends based on Adobe XD or Figma designs, using JQuery, SASS, Tailwind, and Twig.|\nDeveloped interactive games using JavaScript and Adobe Animate.|\nBuilt web apps using React.js, Redux, and TypeScript.|\nCompleted small backend tasks using the Symfony PHP framework.",
        "job_2$technologies": "Twig, SASS, Tailwind, React.js, React Native, Symfony",
        "job_3$title": "Frontend Developer",
        "job_3$from": "August 2018",
        "job_3$to": "September 2020",
        "job_3$company": "Addazzle Mgmt",
        "job_3$description": "As part of my role, I maintained and created new e-commerce websites.",
        "job_3$keypoints": "Built single-page applications (SPA) using React.js, CSS3, and JavaScript ES6.|\nUpdated previously-built projects to use React Router and Redux.|\nUpdated projects to leverage React Hooks",
        "job_3$technologies": "HTML, CSS, Javascript, React.js",
    },
};